# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/uauser/CLionProjects/TRAM/Tram_SECSPEC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/uauser/CLionProjects/TRAM/Tram_SECSPEC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uauser/CLionProjects/TRAM/Tram_SECSPEC/CMakeFiles /home/uauser/CLionProjects/TRAM/Tram_SECSPEC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uauser/CLionProjects/TRAM/Tram_SECSPEC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tram_Netwerk

# Build rule for target.
Tram_Netwerk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tram_Netwerk
.PHONY : Tram_Netwerk

# fast build rule for target.
Tram_Netwerk/fast:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/build
.PHONY : Tram_Netwerk/fast

#=============================================================================
# Target rules for targets named Tram_Netwerk_debug

# Build rule for target.
Tram_Netwerk_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tram_Netwerk_debug
.PHONY : Tram_Netwerk_debug

# fast build rule for target.
Tram_Netwerk_debug/fast:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/build
.PHONY : Tram_Netwerk_debug/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f gtest/lib/googletest-master/googlemock/CMakeFiles/gmock.dir/build.make gtest/lib/googletest-master/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f gtest/lib/googletest-master/googlemock/CMakeFiles/gmock_main.dir/build.make gtest/lib/googletest-master/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/lib/googletest-master/googlemock/gtest/CMakeFiles/gtest.dir/build.make gtest/lib/googletest-master/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/lib/googletest-master/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make gtest/lib/googletest-master/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Tests/SystemDomainTests.o: Tests/SystemDomainTests.cpp.o

.PHONY : Tests/SystemDomainTests.o

# target to build an object file
Tests/SystemDomainTests.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemDomainTests.cpp.o
.PHONY : Tests/SystemDomainTests.cpp.o

Tests/SystemDomainTests.i: Tests/SystemDomainTests.cpp.i

.PHONY : Tests/SystemDomainTests.i

# target to preprocess a source file
Tests/SystemDomainTests.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemDomainTests.cpp.i
.PHONY : Tests/SystemDomainTests.cpp.i

Tests/SystemDomainTests.s: Tests/SystemDomainTests.cpp.s

.PHONY : Tests/SystemDomainTests.s

# target to generate assembly for a file
Tests/SystemDomainTests.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemDomainTests.cpp.s
.PHONY : Tests/SystemDomainTests.cpp.s

Tests/SystemInputTests.o: Tests/SystemInputTests.cpp.o

.PHONY : Tests/SystemInputTests.o

# target to build an object file
Tests/SystemInputTests.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemInputTests.cpp.o
.PHONY : Tests/SystemInputTests.cpp.o

Tests/SystemInputTests.i: Tests/SystemInputTests.cpp.i

.PHONY : Tests/SystemInputTests.i

# target to preprocess a source file
Tests/SystemInputTests.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemInputTests.cpp.i
.PHONY : Tests/SystemInputTests.cpp.i

Tests/SystemInputTests.s: Tests/SystemInputTests.cpp.s

.PHONY : Tests/SystemInputTests.s

# target to generate assembly for a file
Tests/SystemInputTests.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemInputTests.cpp.s
.PHONY : Tests/SystemInputTests.cpp.s

Tests/SystemOutputTests.o: Tests/SystemOutputTests.cpp.o

.PHONY : Tests/SystemOutputTests.o

# target to build an object file
Tests/SystemOutputTests.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemOutputTests.cpp.o
.PHONY : Tests/SystemOutputTests.cpp.o

Tests/SystemOutputTests.i: Tests/SystemOutputTests.cpp.i

.PHONY : Tests/SystemOutputTests.i

# target to preprocess a source file
Tests/SystemOutputTests.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemOutputTests.cpp.i
.PHONY : Tests/SystemOutputTests.cpp.i

Tests/SystemOutputTests.s: Tests/SystemOutputTests.cpp.s

.PHONY : Tests/SystemOutputTests.s

# target to generate assembly for a file
Tests/SystemOutputTests.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemOutputTests.cpp.s
.PHONY : Tests/SystemOutputTests.cpp.s

Tests/SystemTests.o: Tests/SystemTests.cpp.o

.PHONY : Tests/SystemTests.o

# target to build an object file
Tests/SystemTests.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemTests.cpp.o
.PHONY : Tests/SystemTests.cpp.o

Tests/SystemTests.i: Tests/SystemTests.cpp.i

.PHONY : Tests/SystemTests.i

# target to preprocess a source file
Tests/SystemTests.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemTests.cpp.i
.PHONY : Tests/SystemTests.cpp.i

Tests/SystemTests.s: Tests/SystemTests.cpp.s

.PHONY : Tests/SystemTests.s

# target to generate assembly for a file
Tests/SystemTests.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/SystemTests.cpp.s
.PHONY : Tests/SystemTests.cpp.s

Tests/TestUtils.o: Tests/TestUtils.cpp.o

.PHONY : Tests/TestUtils.o

# target to build an object file
Tests/TestUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/TestUtils.cpp.o
.PHONY : Tests/TestUtils.cpp.o

Tests/TestUtils.i: Tests/TestUtils.cpp.i

.PHONY : Tests/TestUtils.i

# target to preprocess a source file
Tests/TestUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/TestUtils.cpp.i
.PHONY : Tests/TestUtils.cpp.i

Tests/TestUtils.s: Tests/TestUtils.cpp.s

.PHONY : Tests/TestUtils.s

# target to generate assembly for a file
Tests/TestUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/Tests/TestUtils.cpp.s
.PHONY : Tests/TestUtils.cpp.s

src/Parser/Parser.o: src/Parser/Parser.cpp.o

.PHONY : src/Parser/Parser.o

# target to build an object file
src/Parser/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Parser/Parser.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Parser/Parser.cpp.o
.PHONY : src/Parser/Parser.cpp.o

src/Parser/Parser.i: src/Parser/Parser.cpp.i

.PHONY : src/Parser/Parser.i

# target to preprocess a source file
src/Parser/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Parser/Parser.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.cpp.i

src/Parser/Parser.s: src/Parser/Parser.cpp.s

.PHONY : src/Parser/Parser.s

# target to generate assembly for a file
src/Parser/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Parser/Parser.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.cpp.s

src/Passagier/Passagier.o: src/Passagier/Passagier.cpp.o

.PHONY : src/Passagier/Passagier.o

# target to build an object file
src/Passagier/Passagier.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Passagier/Passagier.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Passagier/Passagier.cpp.o
.PHONY : src/Passagier/Passagier.cpp.o

src/Passagier/Passagier.i: src/Passagier/Passagier.cpp.i

.PHONY : src/Passagier/Passagier.i

# target to preprocess a source file
src/Passagier/Passagier.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Passagier/Passagier.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Passagier/Passagier.cpp.i
.PHONY : src/Passagier/Passagier.cpp.i

src/Passagier/Passagier.s: src/Passagier/Passagier.cpp.s

.PHONY : src/Passagier/Passagier.s

# target to generate assembly for a file
src/Passagier/Passagier.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Passagier/Passagier.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Passagier/Passagier.cpp.s
.PHONY : src/Passagier/Passagier.cpp.s

src/Spoor/Spoor.o: src/Spoor/Spoor.cpp.o

.PHONY : src/Spoor/Spoor.o

# target to build an object file
src/Spoor/Spoor.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Spoor/Spoor.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Spoor/Spoor.cpp.o
.PHONY : src/Spoor/Spoor.cpp.o

src/Spoor/Spoor.i: src/Spoor/Spoor.cpp.i

.PHONY : src/Spoor/Spoor.i

# target to preprocess a source file
src/Spoor/Spoor.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Spoor/Spoor.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Spoor/Spoor.cpp.i
.PHONY : src/Spoor/Spoor.cpp.i

src/Spoor/Spoor.s: src/Spoor/Spoor.cpp.s

.PHONY : src/Spoor/Spoor.s

# target to generate assembly for a file
src/Spoor/Spoor.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Spoor/Spoor.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Spoor/Spoor.cpp.s
.PHONY : src/Spoor/Spoor.cpp.s

src/Station/Halte.o: src/Station/Halte.cpp.o

.PHONY : src/Station/Halte.o

# target to build an object file
src/Station/Halte.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Halte.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Halte.cpp.o
.PHONY : src/Station/Halte.cpp.o

src/Station/Halte.i: src/Station/Halte.cpp.i

.PHONY : src/Station/Halte.i

# target to preprocess a source file
src/Station/Halte.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Halte.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Halte.cpp.i
.PHONY : src/Station/Halte.cpp.i

src/Station/Halte.s: src/Station/Halte.cpp.s

.PHONY : src/Station/Halte.s

# target to generate assembly for a file
src/Station/Halte.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Halte.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Halte.cpp.s
.PHONY : src/Station/Halte.cpp.s

src/Station/Metrostation.o: src/Station/Metrostation.cpp.o

.PHONY : src/Station/Metrostation.o

# target to build an object file
src/Station/Metrostation.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Metrostation.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Metrostation.cpp.o
.PHONY : src/Station/Metrostation.cpp.o

src/Station/Metrostation.i: src/Station/Metrostation.cpp.i

.PHONY : src/Station/Metrostation.i

# target to preprocess a source file
src/Station/Metrostation.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Metrostation.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Metrostation.cpp.i
.PHONY : src/Station/Metrostation.cpp.i

src/Station/Metrostation.s: src/Station/Metrostation.cpp.s

.PHONY : src/Station/Metrostation.s

# target to generate assembly for a file
src/Station/Metrostation.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Metrostation.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Metrostation.cpp.s
.PHONY : src/Station/Metrostation.cpp.s

src/Station/Station.o: src/Station/Station.cpp.o

.PHONY : src/Station/Station.o

# target to build an object file
src/Station/Station.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Station.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Station.cpp.o
.PHONY : src/Station/Station.cpp.o

src/Station/Station.i: src/Station/Station.cpp.i

.PHONY : src/Station/Station.i

# target to preprocess a source file
src/Station/Station.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Station.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Station.cpp.i
.PHONY : src/Station/Station.cpp.i

src/Station/Station.s: src/Station/Station.cpp.s

.PHONY : src/Station/Station.s

# target to generate assembly for a file
src/Station/Station.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Station/Station.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Station/Station.cpp.s
.PHONY : src/Station/Station.cpp.s

src/System/System.o: src/System/System.cpp.o

.PHONY : src/System/System.o

# target to build an object file
src/System/System.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/System/System.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/System/System.cpp.o
.PHONY : src/System/System.cpp.o

src/System/System.i: src/System/System.cpp.i

.PHONY : src/System/System.i

# target to preprocess a source file
src/System/System.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/System/System.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/System/System.cpp.i
.PHONY : src/System/System.cpp.i

src/System/System.s: src/System/System.cpp.s

.PHONY : src/System/System.s

# target to generate assembly for a file
src/System/System.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/System/System.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/System/System.cpp.s
.PHONY : src/System/System.cpp.s

src/Tram/Albatros.o: src/Tram/Albatros.cpp.o

.PHONY : src/Tram/Albatros.o

# target to build an object file
src/Tram/Albatros.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Albatros.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Albatros.cpp.o
.PHONY : src/Tram/Albatros.cpp.o

src/Tram/Albatros.i: src/Tram/Albatros.cpp.i

.PHONY : src/Tram/Albatros.i

# target to preprocess a source file
src/Tram/Albatros.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Albatros.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Albatros.cpp.i
.PHONY : src/Tram/Albatros.cpp.i

src/Tram/Albatros.s: src/Tram/Albatros.cpp.s

.PHONY : src/Tram/Albatros.s

# target to generate assembly for a file
src/Tram/Albatros.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Albatros.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Albatros.cpp.s
.PHONY : src/Tram/Albatros.cpp.s

src/Tram/PCC.o: src/Tram/PCC.cpp.o

.PHONY : src/Tram/PCC.o

# target to build an object file
src/Tram/PCC.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/PCC.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/PCC.cpp.o
.PHONY : src/Tram/PCC.cpp.o

src/Tram/PCC.i: src/Tram/PCC.cpp.i

.PHONY : src/Tram/PCC.i

# target to preprocess a source file
src/Tram/PCC.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/PCC.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/PCC.cpp.i
.PHONY : src/Tram/PCC.cpp.i

src/Tram/PCC.s: src/Tram/PCC.cpp.s

.PHONY : src/Tram/PCC.s

# target to generate assembly for a file
src/Tram/PCC.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/PCC.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/PCC.cpp.s
.PHONY : src/Tram/PCC.cpp.s

src/Tram/Tram.o: src/Tram/Tram.cpp.o

.PHONY : src/Tram/Tram.o

# target to build an object file
src/Tram/Tram.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Tram.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Tram.cpp.o
.PHONY : src/Tram/Tram.cpp.o

src/Tram/Tram.i: src/Tram/Tram.cpp.i

.PHONY : src/Tram/Tram.i

# target to preprocess a source file
src/Tram/Tram.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Tram.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Tram.cpp.i
.PHONY : src/Tram/Tram.cpp.i

src/Tram/Tram.s: src/Tram/Tram.cpp.s

.PHONY : src/Tram/Tram.s

# target to generate assembly for a file
src/Tram/Tram.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/Tram/Tram.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/Tram/Tram.cpp.s
.PHONY : src/Tram/Tram.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tinyxml/tinystr.o: src/tinyxml/tinystr.cpp.o

.PHONY : src/tinyxml/tinystr.o

# target to build an object file
src/tinyxml/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinystr.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinystr.cpp.o
.PHONY : src/tinyxml/tinystr.cpp.o

src/tinyxml/tinystr.i: src/tinyxml/tinystr.cpp.i

.PHONY : src/tinyxml/tinystr.i

# target to preprocess a source file
src/tinyxml/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinystr.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinystr.cpp.i
.PHONY : src/tinyxml/tinystr.cpp.i

src/tinyxml/tinystr.s: src/tinyxml/tinystr.cpp.s

.PHONY : src/tinyxml/tinystr.s

# target to generate assembly for a file
src/tinyxml/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinystr.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinystr.cpp.s
.PHONY : src/tinyxml/tinystr.cpp.s

src/tinyxml/tinyxml.o: src/tinyxml/tinyxml.cpp.o

.PHONY : src/tinyxml/tinyxml.o

# target to build an object file
src/tinyxml/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxml.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxml.cpp.o
.PHONY : src/tinyxml/tinyxml.cpp.o

src/tinyxml/tinyxml.i: src/tinyxml/tinyxml.cpp.i

.PHONY : src/tinyxml/tinyxml.i

# target to preprocess a source file
src/tinyxml/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxml.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxml.cpp.i
.PHONY : src/tinyxml/tinyxml.cpp.i

src/tinyxml/tinyxml.s: src/tinyxml/tinyxml.cpp.s

.PHONY : src/tinyxml/tinyxml.s

# target to generate assembly for a file
src/tinyxml/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxml.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxml.cpp.s
.PHONY : src/tinyxml/tinyxml.cpp.s

src/tinyxml/tinyxmlerror.o: src/tinyxml/tinyxmlerror.cpp.o

.PHONY : src/tinyxml/tinyxmlerror.o

# target to build an object file
src/tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlerror.cpp.o
.PHONY : src/tinyxml/tinyxmlerror.cpp.o

src/tinyxml/tinyxmlerror.i: src/tinyxml/tinyxmlerror.cpp.i

.PHONY : src/tinyxml/tinyxmlerror.i

# target to preprocess a source file
src/tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlerror.cpp.i
.PHONY : src/tinyxml/tinyxmlerror.cpp.i

src/tinyxml/tinyxmlerror.s: src/tinyxml/tinyxmlerror.cpp.s

.PHONY : src/tinyxml/tinyxmlerror.s

# target to generate assembly for a file
src/tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlerror.cpp.s
.PHONY : src/tinyxml/tinyxmlerror.cpp.s

src/tinyxml/tinyxmlparser.o: src/tinyxml/tinyxmlparser.cpp.o

.PHONY : src/tinyxml/tinyxmlparser.o

# target to build an object file
src/tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlparser.cpp.o
.PHONY : src/tinyxml/tinyxmlparser.cpp.o

src/tinyxml/tinyxmlparser.i: src/tinyxml/tinyxmlparser.cpp.i

.PHONY : src/tinyxml/tinyxmlparser.i

# target to preprocess a source file
src/tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlparser.cpp.i
.PHONY : src/tinyxml/tinyxmlparser.cpp.i

src/tinyxml/tinyxmlparser.s: src/tinyxml/tinyxmlparser.cpp.s

.PHONY : src/tinyxml/tinyxmlparser.s

# target to generate assembly for a file
src/tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/Tram_Netwerk.dir/build.make CMakeFiles/Tram_Netwerk.dir/src/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) -f CMakeFiles/Tram_Netwerk_debug.dir/build.make CMakeFiles/Tram_Netwerk_debug.dir/src/tinyxml/tinyxmlparser.cpp.s
.PHONY : src/tinyxml/tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Tram_Netwerk"
	@echo "... Tram_Netwerk_debug"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Tests/SystemDomainTests.o"
	@echo "... Tests/SystemDomainTests.i"
	@echo "... Tests/SystemDomainTests.s"
	@echo "... Tests/SystemInputTests.o"
	@echo "... Tests/SystemInputTests.i"
	@echo "... Tests/SystemInputTests.s"
	@echo "... Tests/SystemOutputTests.o"
	@echo "... Tests/SystemOutputTests.i"
	@echo "... Tests/SystemOutputTests.s"
	@echo "... Tests/SystemTests.o"
	@echo "... Tests/SystemTests.i"
	@echo "... Tests/SystemTests.s"
	@echo "... Tests/TestUtils.o"
	@echo "... Tests/TestUtils.i"
	@echo "... Tests/TestUtils.s"
	@echo "... src/Parser/Parser.o"
	@echo "... src/Parser/Parser.i"
	@echo "... src/Parser/Parser.s"
	@echo "... src/Passagier/Passagier.o"
	@echo "... src/Passagier/Passagier.i"
	@echo "... src/Passagier/Passagier.s"
	@echo "... src/Spoor/Spoor.o"
	@echo "... src/Spoor/Spoor.i"
	@echo "... src/Spoor/Spoor.s"
	@echo "... src/Station/Halte.o"
	@echo "... src/Station/Halte.i"
	@echo "... src/Station/Halte.s"
	@echo "... src/Station/Metrostation.o"
	@echo "... src/Station/Metrostation.i"
	@echo "... src/Station/Metrostation.s"
	@echo "... src/Station/Station.o"
	@echo "... src/Station/Station.i"
	@echo "... src/Station/Station.s"
	@echo "... src/System/System.o"
	@echo "... src/System/System.i"
	@echo "... src/System/System.s"
	@echo "... src/Tram/Albatros.o"
	@echo "... src/Tram/Albatros.i"
	@echo "... src/Tram/Albatros.s"
	@echo "... src/Tram/PCC.o"
	@echo "... src/Tram/PCC.i"
	@echo "... src/Tram/PCC.s"
	@echo "... src/Tram/Tram.o"
	@echo "... src/Tram/Tram.i"
	@echo "... src/Tram/Tram.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tinyxml/tinystr.o"
	@echo "... src/tinyxml/tinystr.i"
	@echo "... src/tinyxml/tinystr.s"
	@echo "... src/tinyxml/tinyxml.o"
	@echo "... src/tinyxml/tinyxml.i"
	@echo "... src/tinyxml/tinyxml.s"
	@echo "... src/tinyxml/tinyxmlerror.o"
	@echo "... src/tinyxml/tinyxmlerror.i"
	@echo "... src/tinyxml/tinyxmlerror.s"
	@echo "... src/tinyxml/tinyxmlparser.o"
	@echo "... src/tinyxml/tinyxmlparser.i"
	@echo "... src/tinyxml/tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

